const releases=[
['Sematary','Grave House',2019,['Nevada','Interstate','New Rocks','Orbs','Broken Angel Hospital','Fury Road','Ready for the House','Toolbox','The Wagoner','Dead by Dawn','Skin Mask','Grave House']],
['Sematary','Rainbow Bridge',2019,["God’s Light Burns Upon My Flesh",'Arson','Bunny Suit','Dental Floss','Cemetery','Shotgun','The Great Mothman','Creatine','Goat Man','Cop Killer','Johnny Cutter','1312']],
['Sematary','Rainbow Bridge 2',2020,['Red Mist','Scissor Hands','Chandelier','Desecration','Funeral','My Cutter','We Don’t Dial 911','Hogs','Skincarver','Toothtaker']],
['Sematary','Rainbow Bridge 3',2021,['Murder Ride','I’m a Sinner','Chainsaw Party','Necromanser','Creepin Thru da Woods','Truey Jeans','Skin Mask 2','Meet by the River','Forest Fire','Come With Me to Hell','Louisville Slugger','Crucifixion']],
['Sematary','Screaming Forest',2021,['Hocky Mask','Scarecraw','Moon Shine','Willows','Redwoods','Kamakrazee','Longhorns','Spirits','Rituals','Slaughter House','Public Enemy','Goin’ Mordum']],
['Sematary','Butcher House',2023,['Angelmakers','Babayaga','In Tha Field Where I Found U','Suffer','Hallowed Be My Wrist','Little Lamb','Burn a Cop Car','Smokin Out Da Grave','Hate and Gasoline','Go Dig My Grave','We Don’t Dial 911 2']],
['Sematary','King of the Graveyard',2023,['King of the Graveyard','3AM Gang','House of the Dead','Cutter in the Club','I Don’t Care About Sleep Anymore']],
['Sematary','Bloody Angel',2024,['Wendigo','Bloody Angel','Headlights','Parking Lot Scarecrow','Benadryl Angyl','Barrow Wights','Sacrifyce','Get Money N Die','Smoke Machine','Mordor','Hearse Trucks','Dead Trees']],
['Yung Lean','Unknown Death 2002',2013,['Welcome 2 Unknown Death','Nitevision','Oceans 2001','Gatorade','Hurt','Lightsaber // Saviour','Princess Daisy','Lemonade','Emails','Deathstar // Getting Benjamins','Heal You // Bladerunner','Solarflare','Plastic Boy']],
['Yung Lean','Unknown Memory',2014,['Blommor (Intro)','Blinded','Sunrise Angel','Yoshi City','Ice Cold Smoke','Dog Walk (Intermission)','Don’t Go','Ghosttown','Monster','Volt','Leanworld','Sandman']],
['Yung Lean','Warlord',2016,['Immortal','Highway Patrol','Fantasy','Afghanistan','Hoover','Fire','Stay Down','Eye Contact','More Stacks','AF1s','Hocus Pocus','Shawty U Know What It Do','Miami Ultras','Sippin']],
['Yung Lean','Stranger',2017,['Muddy Sea','Red Bottom Sky','Skimask','Silver Arrows','Metallic Intuition','Push / Lost Weekend','Salute / Pacman','Drop It / Scooter','Hunting My Own Skin','Iceman','Snakeskin / Bullets','Fallen Demon','Agony','Yellowman']],
['Yung Lean','Poison Ivy',2018,['Happy Feet','Friday the 13th','French Hotel','Silicon Wings','Ropeman','Trashy','Sauron','Bender++Girlfriend']],
['Yung Lean','Starz',2020,['My Agenda','Yayo','Boylife in EU','Violence','Outta My Head','Dance in the Dark','Acid at 7/11','Butterfly Paralyzed','Dogboy','Iceheart','Pikachu','Low','Sunset Sunrise','Put Me in a Spell','Starz','Hellraiser']],
['Yung Lean','Stardust',2022,['Bliss','Trip','Gold','Starz2theRainbow','All the Things','Lips','Paradise Lost','SummerTime Blood','Nobody Else','Waterfall','Letting It All Go','Visions']],
['Yung Lean','Psykos',2024,['Coda','Ghosts','Golden God','Still','Sold Out','Enemy','Things Happen','Psykos']]
].map((r,i)=>({artist:r[0],album:r[1],year:r[2],tracks:r[3],color:i<8?['#ed3323','#240a08']:['#b9aa91','#3b4541']}));
const tracks=releases.flatMap((r,ri)=>r.tracks.map((title,ti)=>({...r,title,id:ri+'-'+ti,seed:ri*31+ti*7})));const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const liked=new Set(JSON.parse(localStorage.getItem('liked')||'[]'));let current=-1,playing=false,elapsed=0,start=0,raf,audio,nodes=[],shuffle=false,repeat=false,filtered=[...tracks];
function toast(x){let e=$('#toast');e.textContent=x;e.classList.add('show');clearTimeout(e.t);e.t=setTimeout(()=>e.classList.remove('show'),1600)}
function row(t,i){return `<div class="track-row ${tracks[current]?.id===t.id?'playing':''}" data-id="${t.id}"><span>${String(i+1).padStart(2,'0')}</span><span class="track-name"><span class="track-thumb" style="background:linear-gradient(135deg,${t.color})">${t.artist==='Sematary'?'S':'YL'}</span><span><b>${t.title}</b><small>${t.artist}</small></span></span><span>${t.album}</span><span>${t.year}</span><button class="track-like ${liked.has(t.id)?'liked':''}" data-like="${t.id}">${liked.has(t.id)?'♥':'♡'}</button></div>`}
function render(list=filtered,target=$('#trackList')){target.innerHTML=list.length?list.map(row).join(''):'<div class="empty-state"><h2>Здесь пока пусто</h2><p>Добавь треки сердцем.</p></div>'}
function featured(){$('#featuredGrid').innerHTML=[6,7,11,14].map(i=>{let r=releases[i];return `<article class="album-card" data-album="${r.album}"><div class="album-cover" style="--c1:${r.color[0]};--c2:${r.color[1]}">${r.artist==='Sematary'?'S':'YL'}<button class="card-play">▶</button></div><h4>${r.album}</h4><p>${r.artist} • ${r.year}</p></article>`}).join('')}
function setView(n){$$('.view').forEach(x=>x.classList.add('hidden'));$('#'+n+'View').classList.remove('hidden');$$('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===n));if(n==='library')render(tracks.filter(t=>liked.has(t.id)),$('#libraryList'));if(n==='search')$('#searchView').innerHTML=$('#searchInput').value?`<div class="section-head"><div><span>SEARCH</span><h3>Результаты: ${filtered.length}</h3></div></div><div class="track-list">${filtered.map(row).join('')}</div>`:'<div class="empty-state"><h2>Найди свой звук</h2><p>Начни вводить название трека, артиста или альбома.</p></div>'}
function choose(i,go=true){if(i<0)return;stop();current=i;elapsed=0;let t=tracks[i];$('#currentTitle').textContent=t.title;$('#currentArtist').textContent=t.artist+' • '+t.album;$('#miniCover').textContent=t.artist==='Sematary'?'S':'YL';render();if(go)play()}
function sound(t){if(!window.AudioContext)return;audio=audio||new AudioContext();audio.resume();let master=audio.createGain();master.gain.value=$('#volume').value/600;master.connect(audio.destination);let now=audio.currentTime,scale=t.artist==='Sematary'?[55,65,73,82]:[65,78,98,116];for(let s=0;s<30;s+=.5){let o=audio.createOscillator(),g=audio.createGain();o.type=t.artist==='Sematary'?'sawtooth':'triangle';o.frequency.value=scale[(s*2+t.seed)%4|0];g.gain.setValueAtTime(.12,now+s);g.gain.exponentialRampToValueAtTime(.001,now+s+.25);o.connect(g);g.connect(master);o.start(now+s);o.stop(now+s+.3);nodes.push(o)}}
function stop(){playing=false;nodes.forEach(n=>{try{n.stop()}catch{}});nodes=[];cancelAnimationFrame(raf);$('#playBtn').textContent='▶'}function play(){if(current<0)return choose(tracks.findIndex(t=>t.album==='King of the Graveyard'));playing=true;start=performance.now()-elapsed*1000;sound(tracks[current]);$('#playBtn').textContent='Ⅱ';tick()}function toggle(){playing?stop():play()}function tick(){if(!playing)return;elapsed=(performance.now()-start)/1000;$('#elapsed').textContent='0:'+String(elapsed|0).padStart(2,'0');$('#progress').value=elapsed/30*100;if(elapsed>=30)return repeat?(elapsed=0,start=performance.now(),sound(tracks[current])):next();raf=requestAnimationFrame(tick)}function next(){let go=playing;stop();choose(shuffle?Math.random()*tracks.length|0:(current+1)%tracks.length,go)}
function heart(id=tracks[current]?.id){if(!id)return;liked.has(id)?liked.delete(id):liked.add(id);localStorage.setItem('liked',JSON.stringify([...liked]));render();$('#likeCurrent').textContent=liked.has(id)?'♥':'♡';toast(liked.has(id)?'Добавлено в любимые':'Удалено')}
function clicks(e){let h=e.target.closest('[data-like]');if(h){e.stopPropagation();return heart(h.dataset.like)}let r=e.target.closest('.track-row');if(r){let i=tracks.findIndex(t=>t.id===r.dataset.id);i===current?toggle():choose(i)}}
$('#enterBtn').onclick=()=>{$('#intro').classList.add('dismissed');$('#app').classList.remove('is-hidden')};featured();render();$('#trackList').onclick=clicks;$('#searchView').onclick=clicks;$('#libraryList').onclick=clicks;$('#featuredGrid').onclick=e=>{let c=e.target.closest('[data-album]');if(c)choose(tracks.findIndex(t=>t.album===c.dataset.album))};$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#likedNav').onclick=()=>setView('library');$('#searchInput').oninput=e=>{let q=e.target.value.toLowerCase();filtered=tracks.filter(t=>(t.title+t.artist+t.album).toLowerCase().includes(q));setView(q?'search':'home')};$$('.chip').forEach(b=>b.onclick=()=>{$$('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');filtered=tracks.filter(t=>b.dataset.artist==='all'||t.artist===b.dataset.artist);render()});$('#playBtn').onclick=toggle;$('#nextBtn').onclick=next;$('#prevBtn').onclick=()=>choose(Math.max(0,current-1));$('#likeCurrent').onclick=()=>heart();$('#heroPlay').onclick=()=>choose(tracks.findIndex(t=>t.album==='King of the Graveyard'));$('#shuffleAll').onclick=()=>choose(Math.random()*tracks.length|0);$('#shuffleBtn').onclick=()=>{shuffle=!shuffle;toast('Shuffle '+(shuffle?'on':'off'))};$('#repeatBtn').onclick=()=>{repeat=!repeat;toast('Repeat '+(repeat?'on':'off'))};$('#heroLike').onclick=()=>{releases[6].tracks.forEach(n=>liked.add(tracks.find(t=>t.title===n).id));localStorage.setItem('liked',JSON.stringify([...liked]));toast('Альбом сохранён');render()};$$('[data-jump]').forEach(b=>b.onclick=()=>$('#'+b.dataset.jump).scrollIntoView());document.onkeydown=e=>{if(e.code==='Space'&&e.target.tagName!=='INPUT'){e.preventDefault();toggle()}};